### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by silvandeleemput** [ClimenteA/pyvan#12]
@ClimenteA Hi, I really enjoy the simplicity of your pyvan library. For my work, I needed to build a stand-alone python application and with the help of your library, I succeeded in a few hours. I would really like to use your library however I couldn't find a license in your repository. Could I interest you in adding a license to your repository? 

Personally, I have always enjoyed the MIT or Apache licenses for small open-source projects.

Here are the docs on GitHub for your convenience: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by ClimenteA** [comment]
I'm glad it worked!

**Comment by silvandeleemput** [comment]
@ClimenteA Thank you very much for the quick response!
