### ISSUE TITLE
Feature request: option for installing from an existing requirements.txt file

### ISSUE THREAD

**Issue by silvandeleemput** [ClimenteA/pyvan#13]
As mentioned in #12, I have been using your pyvan library to build a stand-alone python application, for which pyvan has helped greatly to achieve the goal. However, in my project there is already a requirements.txt file at the root, I noticed that your script currently overrides during the build. Would it be possible to provide an option to use an existing requirements.txt instead?

I know that as a workaround I could parse the lines of the existing requirements.txt file and provide them line by line to the `OPTIONS["install_only_these_modules"]`, which would technically achieve the same thing. But I think that it is cleaner to provide an explicit option for providing a requirements.txt file explicitly.

If you agree and it is not too much work I could make a PR for this.

**Comment by ClimenteA** [comment]
It uses pip freeze and pipreqs to gather automatically the modules needed.
An option "install_requirements": True would be nice.
A PR would be appreciated.
