### ISSUE TITLE
PYVAN AND TKINTER ISSUE

### ISSUE THREAD

**Issue by charisad** [ClimenteA/pyvan#33]
Pyvan not able to install Tkinter as a module. When I run the command pyvan main.py, after I open the dist folder to run the executable file. I get the error  **from tkinter import Tk,Label, StringVar, Entry, Button ModuleNotFoundError: No module named 'tkinter'**. Can you please advise on this.

**Comment by ClimenteA** [comment]
Go in dist/Scripts folder and install them manually with `pip install tkinter`.

**Comment by charisad** [comment]
> 
I am using python 3.11. Got this error when i tried to install tkinter in dist/Scripts
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter

**Comment by ClimenteA** [comment]
The embeded python used by pyvan doesn't come with tkinter module and it seems it's not available as a package on pypi.
Try to follow this:
 https://stackoverflow.com/questions/37710205/python-embeddable-zip-install-tkinter

**Comment by charisad** [comment]
> The embeded python used by pyvan doesn't come with tkinter module and it seems it's not available as a package on pypi. Try to follow this: https://stackoverflow.com/questions/37710205/python-embeddable-zip-install-tkinter

The embedded python created by pyvan is not having the .\DLLs folder. Should I create one? I actually did what they instructed but still not working

**Comment by charisad** [comment]
I can share my script with you so you see the challenge @ClimenteA . So you assist with the proposed solution https://stackoverflow.com/questions/37710205/python-embeddable-zip-install-tkinter in pyvan. Kindly share you email if you are willing. Thank you

**Comment by charisad** [comment]
Hi @ClimenteA , thanks for your support I switched from tkinter to PyQt. It works fine.
