### ISSUE TITLE
Requirement.txt python module installation.

### ISSUE THREAD

**Issue by charisad** [ClimenteA/pyvan#34]
Want to install the python modules in the requirement.txt? With this command, pip install --target /path/to/folder module. Where should I point the path to in the pydist folder?

**Comment by ClimenteA** [comment]
It should pick up automatically the requirements if you run the pyvan command inside the folder where you have the script and you have next to your script (main.py/run.py/app.py or how you've named it) the requirements.txt file.

**Comment by charisad** [comment]
When I run the pyvan command I see all the modules in the requirements.txt file trying to be installed in the terminal then "Requirement already satisfied" for all the modules shows up. When I navigate to the Libs/site-packages I don't find them there.

**Comment by charisad** [comment]
Can you share a sample van.py script that works for me to see.

**Comment by ClimenteA** [comment]
Go here and tweak around: https://github.com/ClimenteA/pyvan/tree/master/examples

**Comment by charisad** [comment]
Thanks issue resolved
