### ISSUE TITLE
Output is quite verbose - is it possible to add a 'quiet' mode?

### ISSUE THREAD

**Issue by mrseanryan** [ClimenteA/pyvan#37]
Thank you for creating pyvan, it is very useful.

question - is it possible to make the output less verbose:

For example only show warnings or errors ?

**Comment by ClimenteA** [comment]
A flag to make output less verbose could be added. 
I'll keep this open until I get some time for it.

**Comment by ClimenteA** [comment]
added the verbose flag (checkout readme)
