### ISSUE TITLE
Request new patch release version of Pyvan for PyPI

### ISSUE THREAD

**Issue by silvandeleemput** [ClimenteA/pyvan#39]
Hi, @ClimenteA. I hope you are doing well. I just got an issue posted at the gen-exe repo about missing spaces https://github.com/silvandeleemput/gen-exe/issues/4. This was ultimately related to an omission on my part in generating the executable command in Pyvan. However, to my pleasant surprise, I saw that this was already fixed in the master branch by #36, thanks to @jwillkomm-fionec. 

This fix is however not yet present if you pull from the PyPI repository through pip. Could you maybe create a new patch release for Pyvan on PyPI?

**Comment by ClimenteA** [comment]
Hi @silvandeleemput! all good.

I will push tomorrow to pypi the newer version with @jwillkomm-fionec fix.

Thank you!

**Comment by ClimenteA** [comment]
Pushed to pypi new version pyvan 1.2.3
