### ISSUE TITLE
Linux bat file

### ISSUE THREAD

**Issue by johnyquest7** [ClimenteA/pyvan#8]
Could you create a different distribution for linux. 
Bat file does not work in linux

**Comment by ClimenteA** [comment]
Linux and Mac have python already installed.

You can distribute the scripts by creating a bash file which starts python and your script.

The bash files in linux ends with ".sh"

Try to rename the `main.bat` to `main.sh` and see if it works.

Or copy contents from `main.bat` to a new file named `main.sh`
