### ISSUE TITLE
Pyvan on Windows

### ISSUE THREAD

**Issue by NgoziOkereke** [ClimenteA/pyvan#9]
Hello, I have attempted using Pyvan on Windows and always end up with many errors. I did however get it to work with my Cygwin terminal. However, when it works on Cygwin it does not launch the application in any other folder. 

The current errors are Access Denied and Permission Errors, when attempting to access the requirements.txt file. I bypassed this by putting in the needed modules as part of OPTIONS. However now, pip is not found, pip is in the Downloads folder and was found while using the Cygwin terminal. I know this might be a minor issue but I am having a hard time understanding it. Hope to hear back from anyone who can help soon. Thanks.

**Comment by NgoziOkereke** [comment]
I found a work around.

**Comment by NgoziOkereke** [comment]
I have been able to package the application but when trying to run it, it just flashes the command prompt and does not launch. I ran the entry script from the dist folder it that script launches the application well. However the bat file does not.

**Comment by ClimenteA** [comment]
[The function that creates the batch file](https://github.com/ClimenteA/pyvan/blob/9c360c62e2fa0ffe307c5d974136ac891180eb72/src/pyvan.py#L195) is just doing this `"START python " + OPTIONS["main_file_name"]` that assumes that the modules/packages you made are next to `python.exe` file.

[Add a `pause` keyword in the batch file at the end to see the error](https://coderwall.com/p/jexjlw/pause-on-error-in-batch-file) 

There are some modules that cause issues when installed on python embedded version..

**Comment by NgoziOkereke** [comment]
Thank you for responding.

I pause the batch file, and the error I get is "File Not Found". I do not know what file in particular this is referring to. The main file is available in the dist folder and when I run "python <main_file>.py" from the dist folder, it launches the app.

**Comment by ClimenteA** [comment]
Try to remove temporarily python from environment variables and try again (maybe it uses the global installed python). 
If it works from cmd it should work from the batch file.

**Comment by NgoziOkereke** [comment]
I decided to use pyinstaller, because I did not know how to resolve the issue. Thank you for helping.
